# This workflow pushes any changes to a private mirror that runs the
# test suite using a self-hosted runner. 
name: Push to private

on:
  push:
  # workflow_dispatch:

env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "REPOSITORY_NAME=${{ github.repository }}"
      shell: bash
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    # Start ssh-agent but set it to use the same ssh_auth_sock value.
    # The agent will be running in all steps after this, so it
    # should be one of the first.
    - name: Setup SSH passphrase
      env:
        SSH_PASSPHRASE: ${{secrets.KEY_PASSPHRASE}}
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_MIRROR_REPO}}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

    # Debug print out the added identities. This will prove SSH_AUTH_SOCK
    # is persisted across job steps
    - name: Print ssh-add identities
      run: ssh-add -l

    - name: Set username
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "${{ secrets.USERNAME }}"
    - name: Push changes
      if: ${{ github.repository == 'stfc/PSyclone' }}
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        force: true
        tags: false
        branch: ${{ github.ref }}
        repository: arporter/PSyclone-mirror
