# This workflow pushes any changes to a private mirror that runs the
# test suite using a self-hosted runner. 
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Set username
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "${{ secrets.USERNAME }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SECRET_TOKEN }}
        branch: ${{ github.ref }}
        repository: arporter/PSyclone-mirror
